---
- hosts: all
  tasks:
    - name: Create Jenkins network on Docker
      shell: "docker network create jenkins"
    - name: Run DIND image
      shell: "docker run --name jenkins-docker --rm --detach --privileged --network jenkins --network-alias docker --env DOCKER_TLS_CERTDIR=/certs --volume jenkins-docker-certs:/certs/client --volume jenkins-data:/var/jenkins_home --publish 2376:2376 docker:dind --storage-driver overlay2"
    - name: Copy Jenkins image Dockerfile
      copy:
        src: Dockerfile
        dest: Dockerfile
        owner: '{{ ansible_user }}'
    - name: Build Jenkins Blue Ocean image
      shell: "docker build -t myjenkins-blueocean:1.1 ."
    - name: Run Jenkins Blue Ocean image
      shell: "docker run --name jenkins-blueocean --rm --detach --network jenkins --env DOCKER_HOST=tcp://docker:2376 --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1 --publish 9090:8080 --publish 50000:50000 --volume jenkins-data:/var/jenkins_home --volume jenkins-docker-certs:/certs/client:ro myjenkins-blueocean:1.1"
