---
- hosts: all
  tasks:
    - name: Update packages
      become: 'yes'
      apt:
        update_cache: 'yes'
        force_apt_get: 'yes'
    - name: Install packages to let APT use packges over HTTPS
      become: 'yes'
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        update_cache: 'yes'
    - name: Add Docker repository GPG key
      become: 'yes'
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
    - name: Add Docker repository
      become: 'yes'
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable'
        update_cache: 'yes'
    - name: Install docker
      become: 'yes'
      apt:
        name: docker-ce
        update_cache: 'yes'
    - name: Add docker group to current user
      become: 'yes'
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: 'yes'
